project:
  type: website
  output-dir: docs

website:
  title: "Data Science Cheat Sheet"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Data Science"
        contents:
          - data_transformation.qmd
          - data_timeseries.qmd
          - data_visualization.qmd
      - section: "Machine Learning"
        contents:
          - machine_learning_regression.qmd
          - machine_learning_classification.qmd
          
  navbar:
    left:
      - href: data_transformation.qmd
        text: Home
      - about.qmd

format:
  html:
    #page-layout: custom
    theme:
      light: Minty
      dark: Darkly
    fontsize: 16px
    toc-title: Table of Contents
    code-fold: show
    code-tools: TRUE
    toc: TRUE
    toc-depth: 3
    smooth-scroll: TRUE

editor: visual

